name: Docker

on:
  push:
    # Publish `master` as Docker `late`image.
    branches:
      - master

    # Publish `v1.2.3` tags as  releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:
  #build 
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
      name: Check out code
    - uses: docker/build-push-action@v1
      name: Build & push Docker image
      with:
        dockerfile: configServer/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: spbravo/gitops
        tags: version1.1
